"""empty message

Revision ID: 0d5a09a35a6a
Revises: d2319de6cb9c
Create Date: 2020-02-23 20:06:44.277778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5a09a35a6a'
down_revision = 'd2319de6cb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shows', 'Venue', ['venue_id'], ['id'])
    op.drop_column('shows', 'artist_image_link')
    op.drop_column('shows', 'artist_name')
    op.drop_column('shows', 'venue_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('artist_image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
